### ISSUE TITLE
vpu/gpu libraries ?!?

### ISSUE THREAD

**Issue by ovidiu31** [allwinner-zh/media-codec#1]
greetings

Would be possible to publish the A8x (sun9i) vpu/gpu libs and sources (even closed binaries are ok) in order to be able to run linux Desktop distributions or even Linux Kodi  with vpu/gpu  hardware acceleration support 

Thank you

**Comment by javqui** [comment]
Will be a very important contribution, even closed binaries with some basic documentation.
Thanks in advance.

**Comment by rzk** [comment]
What do you mean by "Kodi with vpu/gpu"? You can already run Kodi with software decoding and GPU rendering, but that might choke on high resolutions.

To get hardware video decoding, we need to make use OpenMAX libraries that are result of building this repository, since Allwinner posted Hard-Float blob libraries, they've meant these to be used on native linux setup.

Please, don't expect Allwinner to fix Kodi, first we just need to get some standard gstreamer rendering atleast something with this through gst-omx and then try to run such monster as Kodi.

**Comment by ovidiu31** [comment]
@rzk 
I don't expect Allwinner to fix Kodi ...  
I expect allwinner to liase with Team kodi an provide them the A80 vpu code to solve already this issue together.
Same way was  proceeding Amlogic too and other chinese SoC manufacturer. 
They have sent vpu portion of the code to integrate it in Kodi repositories to be able to compile linux version of Kodi.

There is a version of ubuntu runing on allwiner a80 with some hardware vpu gpu acceleration working at least for MKV h264 video content .... but  youtube from browser and html 5 video content is still running jerky quality.

I also want to mention for A80 that even in Android Kodi playback of live TV 1080i streams are compromised and image is in slow motion.

**Comment by rzk** [comment]
> I expect allwinner to liase with Team kodi an provide them the A80 vpu code to solve already this issue together.

That probably won't happen in the way you expect this to happen. Allwinner is SoC manufacturer that provides BSPs to integrators, Kodi is kinda out of scope here.

Just throwing out vpu code will do nothing, you need guys from Kodi team interested in getting cedar working with their project. Question is in manpower, I remember in XBMC for sun4i CedarX days there were only two guys on #linux-sunxi IRC channel working on it, for such big thing as XBMC that was not enough. 

The way that this problem can be solved _easily_, is providing working OpenMAX and then integrating that into your favourite software (for me its gstreamer, but I bet Kodi can use gstreamer).

For having problems with 1080i on Android you should contact Cubietech support (if you have cubieboard4), they have connection to Allwinner and will request support. Android is top priority for Allwinner, so you'll get support if there's really a problem.

**Comment by ovidiu31** [comment]
@rzk 
Well in this case Allwinner SoC's (with all my respect ) are doomed , im really sorry for their soc's and for their work tho i had some hope  after had some discussions with Ben El Baz their marketing manager.
@allwinner-zh 
Seems Kodi won't be an option anytime soon on Allwinner soc's ... too bad ... you guys have lost an huge commercial sales oportunity.

best regards

**Comment by simos** [comment]
For Android, it is possible to get Kodi for Android to work if those Android images provided an OMX implementation with such closed-source libraries. Android images already have GPU acceleration (closed-source libraries from ARM or ImgTec), so it should work. The issue is to get these VPU libraries for "armel/bionic", which is what Android needs.

**Comment by leojrfs** [comment]
@rzk is anyone working on cedar omx integration with gst? What is working/what does need to be done?
